# Linear Algebra for AI/ML - Part 2

This notebook continues from Part 1 with more advanced linear algebra concepts.

**Prerequisites:** Complete Part 1 first (fundamental concepts).

In [1]:
"""
Setup: Import Required Libraries
"""
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg
from mpl_toolkits.mplot3d import Axes3D

np.set_printoptions(precision=4, suppress=True)
print(f"NumPy version: {np.__version__}")

NumPy version: 2.2.6


## 16. Vector Space

A vector space is a set with defined addition and scalar multiplication that satisfy specific axioms.

**ML Application:** Feature spaces, hypothesis spaces, understanding model capacity.

In [2]:
"""
Vector Space

A set V is a vector space over field F if:
1. Closed under addition: u + v ∈ V
2. Closed under scalar multiplication: αv ∈ V
3. Associative: (u + v) + w = u + (v + w)
4. Commutative: u + v = v + u
5. Zero element: ∃ 0 such that v + 0 = v
6. Additive inverse: ∃ -v such that v + (-v) = 0
7. Distributive: α(u + v) = αu + αv
8. Distributive: (α + β)v = αv + βv
9. Associative scalars: α(βv) = (αβ)v
10. Identity: 1v = v
"""

# Example: ℝ³ is a vector space
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
w = np.array([7, 8, 9])
alpha = 2.0
beta = 3.0

print("="*60)
print("Vector Space: ℝ³")
print("="*60)

print(f"\nu = {u}")
print(f"v = {v}")
print(f"w = {w}")
print(f"α = {alpha}, β = {beta}")

# Verify axioms
print("\n" + "-"*60)
print("Verifying Vector Space Axioms:")
print("-"*60)

# 1. Closure under addition
print("\n1. Closure (addition): u + v ∈ ℝ³")
result = u + v
print(f"   u + v = {result} ✓")

# 2. Closure under scalar multiplication
print("\n2. Closure (scalar mult): αv ∈ ℝ³")
result = alpha * v
print(f"   {alpha} × v = {result} ✓")

# 3. Associativity
print("\n3. Associativity: (u + v) + w = u + (v + w)")
left = (u + v) + w
right = u + (v + w)
print(f"   Left:  {left}")
print(f"   Right: {right}")
print(f"   Equal? {np.allclose(left, right)} ✓")

# 4. Commutativity
print("\n4. Commutativity: u + v = v + u")
left = u + v
right = v + u
print(f"   u + v = {left}")
print(f"   v + u = {right}")
print(f"   Equal? {np.allclose(left, right)} ✓")

# 5. Zero element
print("\n5. Zero element: v + 0 = v")
zero = np.zeros(3)
result = v + zero
print(f"   v + 0 = {result}")
print(f"   v     = {v}")
print(f"   Equal? {np.allclose(result, v)} ✓")

# 6. Additive inverse
print("\n6. Additive inverse: v + (-v) = 0")
result = v + (-v)
print(f"   v + (-v) = {result}")
print(f"   Is zero? {np.allclose(result, zero)} ✓")

# 7. Distributivity (scalar over vector addition)
print("\n7. Distributivity: α(u + v) = αu + αv")
left = alpha * (u + v)
right = alpha * u + alpha * v
print(f"   α(u + v) = {left}")
print(f"   αu + αv  = {right}")
print(f"   Equal? {np.allclose(left, right)} ✓")

# 8. Distributivity (scalar addition over vector)
print("\n8. Distributivity: (α + β)v = αv + βv")
left = (alpha + beta) * v
right = alpha * v + beta * v
print(f"   (α + β)v = {left}")
print(f"   αv + βv  = {right}")
print(f"   Equal? {np.allclose(left, right)} ✓")

# 9. Scalar associativity
print("\n9. Scalar associativity: α(βv) = (αβ)v")
left = alpha * (beta * v)
right = (alpha * beta) * v
print(f"   α(βv)  = {left}")
print(f"   (αβ)v  = {right}")
print(f"   Equal? {np.allclose(left, right)} ✓")

# 10. Identity
print("\n10. Identity: 1v = v")
result = 1.0 * v
print(f"    1v = {result}")
print(f"    v  = {v}")
print(f"    Equal? {np.allclose(result, v)} ✓")

print("\n" + "="*60)
print("All axioms verified! ℝ³ is a vector space.")
print("="*60)

Vector Space: ℝ³

u = [1 2 3]
v = [4 5 6]
w = [7 8 9]
α = 2.0, β = 3.0

------------------------------------------------------------
Verifying Vector Space Axioms:
------------------------------------------------------------

1. Closure (addition): u + v ∈ ℝ³
   u + v = [5 7 9] ✓

2. Closure (scalar mult): αv ∈ ℝ³
   2.0 × v = [ 8. 10. 12.] ✓

3. Associativity: (u + v) + w = u + (v + w)
   Left:  [12 15 18]
   Right: [12 15 18]
   Equal? True ✓

4. Commutativity: u + v = v + u
   u + v = [5 7 9]
   v + u = [5 7 9]
   Equal? True ✓

5. Zero element: v + 0 = v
   v + 0 = [4. 5. 6.]
   v     = [4 5 6]
   Equal? True ✓

6. Additive inverse: v + (-v) = 0
   v + (-v) = [0 0 0]
   Is zero? True ✓

7. Distributivity: α(u + v) = αu + αv
   α(u + v) = [10. 14. 18.]
   αu + αv  = [10. 14. 18.]
   Equal? True ✓

8. Distributivity: (α + β)v = αv + βv
   (α + β)v = [20. 25. 30.]
   αv + βv  = [20. 25. 30.]
   Equal? True ✓

9. Scalar associativity: α(βv) = (αβ)v
   α(βv)  = [24. 30. 36.]
   (αβ)v  =

## 17. Linear Combination

A linear combination is formed by scaling vectors and adding them.

**Formula:** y = λ₁v₁ + λ₂v₂ + ... + λₙvₙ

**ML Application:** Feature engineering, basis transformations, neural network outputs.

In [3]:
"""
Linear Combination

Definition:
Given vectors v₁, v₂, ..., vₙ and scalars λ₁, λ₂, ..., λₙ,
a linear combination is:

    y = λ₁v₁ + λ₂v₂ + ... + λₙvₙ

ML Applications:
- Weighted sum in neural networks
- Feature combinations
- Basis changes in PCA
- Ensemble methods (weighted models)
"""

print("="*60)
print("Linear Combinations")
print("="*60)

# Define basis vectors
v1 = np.array([1, 0])
v2 = np.array([0, 1])

print("\nBasis vectors:")
print(f"v₁ = {v1}")
print(f"v₂ = {v2}")

# Example 1: Create point (3, 2) as linear combination
print("\n" + "-"*60)
print("Example 1: Express (3, 2) as linear combination")
print("-"*60)

lambda1 = 3
lambda2 = 2

y = lambda1 * v1 + lambda2 * v2

print(f"\ny = {lambda1}v₁ + {lambda2}v₂")
print(f"  = {lambda1} × {v1} + {lambda2} × {v2}")
print(f"  = {lambda1 * v1} + {lambda2 * v2}")
print(f"  = {y}")

# Example 2: Multiple vectors in ℝ³
print("\n" + "-"*60)
print("Example 2: Linear combination in ℝ³")
print("-"*60)

v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])

print(f"\nv₁ = {v1}")
print(f"v₂ = {v2}")
print(f"v₃ = {v3}")

# Create point (2, -3, 5)
coeffs = np.array([2, -3, 5])
target = coeffs[0]*v1 + coeffs[1]*v2 + coeffs[2]*v3

print(f"\nTarget: {target}")
print(f"\nLinear combination:")
print(f"y = {coeffs[0]}v₁ + {coeffs[1]}v₂ + {coeffs[2]}v₃")
print(f"  = {coeffs[0]} × {v1} + {coeffs[1]} × {v2} + {coeffs[2]} × {v3}")
print(f"  = {target}")

# Example 3: Non-standard basis
print("\n" + "-"*60)
print("Example 3: Non-standard basis vectors")
print("-"*60)

v1 = np.array([1, 1])
v2 = np.array([1, -1])

print(f"\nNew basis:")
print(f"v₁ = {v1}")
print(f"v₂ = {v2}")

# Express (4, 2) in this basis
# Need: λ₁[1,1] + λ₂[1,-1] = [4,2]
# Solve: λ₁ + λ₂ = 4 and λ₁ - λ₂ = 2
lambda1 = 3
lambda2 = 1

result = lambda1 * v1 + lambda2 * v2

print(f"\nExpress [4, 2] in this basis:")
print(f"y = {lambda1}v₁ + {lambda2}v₂")
print(f"  = {lambda1} × {v1} + {lambda2} × {v2}")
print(f"  = {lambda1 * v1} + {lambda2 * v2}")
print(f"  = {result}")

# ML Application: Neural Network
print("\n" + "="*60)
print("ML Application: Neural Network Layer")
print("="*60)

# Input features
x = np.array([2.5, 1.3, -0.7])  # 3 features

# Weights for one neuron (each weight is a coefficient)
w = np.array([0.8, -1.2, 0.5])
b = 0.3  # bias

print(f"\nInput features x: {x}")
print(f"Weights w: {w}")
print(f"Bias b: {b}")

# Linear combination!
z = np.dot(w, x) + b
# Equivalently: z = w[0]*x[0] + w[1]*x[1] + w[2]*x[2] + b

print(f"\nNeuron output (before activation):")
print(f"z = w·x + b")
print(f"  = {w[0]}×{x[0]} + {w[1]}×{x[1]} + {w[2]}×{x[2]} + {b}")
print(f"  = {w[0]*x[0]:.4f} + {w[1]*x[1]:.4f} + {w[2]*x[2]:.4f} + {b}")
print(f"  = {z:.4f}")

print("\n→ This is a linear combination of input features!")
print("→ Each weight determines how much each feature contributes")
print("→ Used in EVERY layer of EVERY neural network")

Linear Combinations

Basis vectors:
v₁ = [1 0]
v₂ = [0 1]

------------------------------------------------------------
Example 1: Express (3, 2) as linear combination
------------------------------------------------------------

y = 3v₁ + 2v₂
  = 3 × [1 0] + 2 × [0 1]
  = [3 0] + [0 2]
  = [3 2]

------------------------------------------------------------
Example 2: Linear combination in ℝ³
------------------------------------------------------------

v₁ = [1 0 0]
v₂ = [0 1 0]
v₃ = [0 0 1]

Target: [ 2 -3  5]

Linear combination:
y = 2v₁ + -3v₂ + 5v₃
  = 2 × [1 0 0] + -3 × [0 1 0] + 5 × [0 0 1]
  = [ 2 -3  5]

------------------------------------------------------------
Example 3: Non-standard basis vectors
------------------------------------------------------------

New basis:
v₁ = [1 1]
v₂ = [ 1 -1]

Express [4, 2] in this basis:
y = 3v₁ + 1v₂
  = 3 × [1 1] + 1 × [ 1 -1]
  = [3 3] + [ 1 -1]
  = [4 2]

ML Application: Neural Network Layer

Input features x: [ 2.5  1.3 -0.7]
Weights

## 18. Span

The span is the set of all possible linear combinations of given vectors.

**ML Application:** Understanding representational capacity, feature coverage, subspace learning.

In [4]:
"""
Span of Vectors

Definition:
The span of vectors {v₁, v₂, ..., vₙ} is the set of all linear combinations:

    span({v₁, ..., vₙ}) = {λ₁v₁ + ... + λₙvₙ : λᵢ ∈ ℝ}

Key Points:
- Span is a subspace
- Can be smaller than the ambient space
- Vectors don't need to be independent

ML Applications:
- PCA: span of top eigenvectors
- Feature space coverage
- Rank of data matrix
"""

print("="*60)
print("Span of Vectors")
print("="*60)

# Example 1: Span of single vector in ℝ²
print("\nExample 1: Span of one vector")
print("-"*60)

v = np.array([1, 2])
print(f"v = {v}")
print(f"\nspan({{v}}) = {{λv : λ ∈ ℝ}}")
print("\nThis is a LINE through the origin:")

# Generate points on this line
lambdas = np.linspace(-2, 2, 5)
for lam in lambdas:
    point = lam * v
    print(f"  λ = {lam:5.1f} → {lam}v = {point}")

print("\n→ Span is 1-dimensional (a line)")
print("→ Cannot reach any point off this line")

# Example 2: Span of two vectors in ℝ²
print("\n" + "="*60)
print("Example 2: Span of two vectors in ℝ²")
print("="*60)

v1 = np.array([1, 0])
v2 = np.array([0, 1])

print(f"\nv₁ = {v1}")
print(f"v₂ = {v2}")
print(f"\nspan({{v₁, v₂}}) = {{λ₁v₁ + λ₂v₂ : λ₁, λ₂ ∈ ℝ}}")
print("\nThis spans ALL of ℝ²:")

# Show we can reach any point
targets = [(3, 2), (-1, 4), (0, 0), (5, -3)]
print("\nSample points we can reach:")
for target in targets:
    lambda1, lambda2 = target
    result = lambda1 * v1 + lambda2 * v2
    print(f"  {lambda1}v₁ + {lambda2}v₂ = {result}")

print("\n→ Span is 2-dimensional (entire plane)")
print("→ Can reach ANY point in ℝ²")

# Example 3: Span of two DEPENDENT vectors
print("\n" + "="*60)
print("Example 3: Span of dependent vectors")
print("="*60)

v1 = np.array([1, 2])
v2 = np.array([2, 4])  # v2 = 2 × v1

print(f"\nv₁ = {v1}")
print(f"v₂ = {v2} = 2 × v₁")
print(f"\nspan({{v₁, v₂}}) = {{λ₁v₁ + λ₂v₂ : λ₁, λ₂ ∈ ℝ}}")

# But this is just a line!
print("\nHowever, since v₂ = 2v₁:")
print("λ₁v₁ + λ₂v₂ = λ₁v₁ + λ₂(2v₁) = (λ₁ + 2λ₂)v₁")
print("\n→ Still just a LINE (same as span({v₁}))")
print("→ Adding dependent vector doesn't expand the span")
print("→ Dimension = 1, not 2")

# Example 4: Span in ℝ³
print("\n" + "="*60)
print("Example 4: Spans in ℝ³")
print("="*60)

# Case 1: One vector
v1 = np.array([1, 0, 0])
print("\nCase 1: One vector")
print(f"span({{v₁}}) where v₁ = {v1}")
print("→ A LINE through origin")
print("→ 1-dimensional subspace of ℝ³")

# Case 2: Two independent vectors
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
print("\nCase 2: Two independent vectors")
print(f"span({{v₁, v₂}}) where v₁ = {v1}, v₂ = {v2}")
print("→ A PLANE through origin (xy-plane)")
print("→ 2-dimensional subspace of ℝ³")

# Case 3: Three independent vectors
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])
print("\nCase 3: Three independent vectors")
print(f"span({{v₁, v₂, v₃}})")
print(f"  v₁ = {v1}")
print(f"  v₂ = {v2}")
print(f"  v₃ = {v3}")
print("→ ALL of ℝ³")
print("→ 3-dimensional (full space)")

# ML Application
print("\n" + "="*60)
print("ML Application: PCA and Feature Space")
print("="*60)

# Create synthetic data
np.random.seed(42)
n_samples = 100

# Data mostly varies in 2 directions
component1 = np.random.randn(n_samples, 1) * 3
component2 = np.random.randn(n_samples, 1) * 1
component3 = np.random.randn(n_samples, 1) * 0.1  # Very small variance

# Mix them
X = np.hstack([component1, component2, component3])

print(f"\nOriginal data: {X.shape}")
print(f"Nominal dimension: 3")

# Compute covariance and eigenvalues
cov = np.cov(X.T)
eigenvalues, eigenvectors = np.linalg.eig(cov)

# Sort by eigenvalue
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

print(f"\nEigenvalues (variance): {eigenvalues}")
print(f"\nInterpretation:")
print(f"→ First direction explains {eigenvalues[0]:.4f} variance")
print(f"→ Second direction explains {eigenvalues[1]:.4f} variance")
print(f"→ Third direction explains {eigenvalues[2]:.4f} variance (negligible!)")

# Top 2 principal components
top_2_components = eigenvectors[:, :2]

print(f"\nTop 2 principal components:")
print(top_2_components)

print(f"\nspan of top 2 components:")
print("→ Captures most of the data's variation")
print("→ Can project data onto this 2D subspace")
print("→ Dimensionality reduction: 3D → 2D")
print("→ Loses minimal information (only 3rd component)")

Span of Vectors

Example 1: Span of one vector
------------------------------------------------------------
v = [1 2]

span({v}) = {λv : λ ∈ ℝ}

This is a LINE through the origin:
  λ =  -2.0 → -2.0v = [-2. -4.]
  λ =  -1.0 → -1.0v = [-1. -2.]
  λ =   0.0 → 0.0v = [0. 0.]
  λ =   1.0 → 1.0v = [1. 2.]
  λ =   2.0 → 2.0v = [2. 4.]

→ Span is 1-dimensional (a line)
→ Cannot reach any point off this line

Example 2: Span of two vectors in ℝ²

v₁ = [1 0]
v₂ = [0 1]

span({v₁, v₂}) = {λ₁v₁ + λ₂v₂ : λ₁, λ₂ ∈ ℝ}

This spans ALL of ℝ²:

Sample points we can reach:
  3v₁ + 2v₂ = [3 2]
  -1v₁ + 4v₂ = [-1  4]
  0v₁ + 0v₂ = [0 0]
  5v₁ + -3v₂ = [ 5 -3]

→ Span is 2-dimensional (entire plane)
→ Can reach ANY point in ℝ²

Example 3: Span of dependent vectors

v₁ = [1 2]
v₂ = [2 4] = 2 × v₁

span({v₁, v₂}) = {λ₁v₁ + λ₂v₂ : λ₁, λ₂ ∈ ℝ}

However, since v₂ = 2v₁:
λ₁v₁ + λ₂v₂ = λ₁v₁ + λ₂(2v₁) = (λ₁ + 2λ₂)v₁

→ Still just a LINE (same as span({v₁}))
→ Adding dependent vector doesn't expand the span
→ Dimen

## 19. Linear Independence

Vectors are linearly independent if none can be written as a combination of others.

**ML Application:** Feature redundancy, basis selection, rank determination.

In [5]:
"""
Linear Independence

Definition:
Vectors {v₁, v₂, ..., vₙ} are linearly independent if:

    λ₁v₁ + λ₂v₂ + ... + λₙvₙ = 0  ⟹  λ₁ = λ₂ = ... = λₙ = 0

In other words:
- Only way to get zero is with all zero coefficients
- No vector is a combination of the others
- Each vector adds new information/direction

Quick Checks:
1. Zero vector present → DEPENDENT
2. More vectors than dimensions → DEPENDENT
3. det(A) ≠ 0 (square matrix) → INDEPENDENT
4. rank(A) = n columns → INDEPENDENT
"""

print("="*60)
print("Linear Independence")
print("="*60)

# Example 1: Independent vectors in ℝ²
print("\nExample 1: INDEPENDENT vectors in ℝ²")
print("-"*60)

v1 = np.array([1, 0])
v2 = np.array([0, 1])

A = np.column_stack([v1, v2])

print(f"v₁ = {v1}")
print(f"v₂ = {v2}")
print(f"\nMatrix A = [v₁ v₂]:")
print(A)

# Check: Can we write 0 as λ₁v₁ + λ₂v₂ with non-zero λ?
# Solve Ax = 0
rank = np.linalg.matrix_rank(A)
det = np.linalg.det(A)

print(f"\nRank: {rank}")
print(f"Determinant: {det}")
print(f"\nSince det ≠ 0 and rank = 2:")
print("→ Vectors are INDEPENDENT ✓")
print("→ Only solution to λ₁v₁ + λ₂v₂ = 0 is λ₁ = λ₂ = 0")

# Example 2: Dependent vectors
print("\n" + "="*60)
print("Example 2: DEPENDENT vectors in ℝ²")
print("="*60)

v1 = np.array([1, 2])
v2 = np.array([2, 4])  # v2 = 2 × v1

A = np.column_stack([v1, v2])

print(f"v₁ = {v1}")
print(f"v₂ = {v2}")
print(f"\nNotice: v₂ = 2 × v₁")
print(f"\nMatrix A = [v₁ v₂]:")
print(A)

rank = np.linalg.matrix_rank(A)
det = np.linalg.det(A)

print(f"\nRank: {rank}")
print(f"Determinant: {det:.10f}")
print(f"\nSince det = 0 and rank < 2:")
print("→ Vectors are DEPENDENT ✗")
print("\nNon-trivial solution exists:")
print("2v₁ + (-1)v₂ = 0")
print(f"Verify: 2 × {v1} + (-1) × {v2} = {2*v1 - v2}")

# Example 3: Three vectors in ℝ³
print("\n" + "="*60)
print("Example 3: Testing independence in ℝ³")
print("="*60)

# Case 3a: Independent
print("\nCase 3a: Independent vectors")
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])

A = np.column_stack([v1, v2, v3])

print(f"v₁ = {v1}")
print(f"v₂ = {v2}")
print(f"v₃ = {v3}")
print(f"\nMatrix A:")
print(A)

rank = np.linalg.matrix_rank(A)
det = np.linalg.det(A)

print(f"\nRank: {rank}")
print(f"Determinant: {det}")
print("→ INDEPENDENT ✓")

# Case 3b: Dependent
print("\nCase 3b: Dependent vectors")
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([5, 7, 9])  # v3 = v1 + v2

A = np.column_stack([v1, v2, v3])

print(f"v₁ = {v1}")
print(f"v₂ = {v2}")
print(f"v₃ = {v3}")
print(f"\nNotice: v₃ = v₁ + v₂")
print(f"Verify: {v1} + {v2} = {v1 + v2}")

print(f"\nMatrix A:")
print(A)

rank = np.linalg.matrix_rank(A)
det = np.linalg.det(A)

print(f"\nRank: {rank}")
print(f"Determinant: {det:.10f}")
print("→ DEPENDENT ✗")
print("\nLinear dependence: v₁ + v₂ - v₃ = 0")

# Example 4: More vectors than dimensions
print("\n" + "="*60)
print("Example 4: More vectors than dimensions")
print("="*60)

# 4 vectors in ℝ³ → Must be dependent!
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])
v4 = np.array([1, 1, 1])

A = np.column_stack([v1, v2, v3, v4])

print(f"\n4 vectors in ℝ³:")
print(f"v₁ = {v1}")
print(f"v₂ = {v2}")
print(f"v₃ = {v3}")
print(f"v₄ = {v4}")

rank = np.linalg.matrix_rank(A)

print(f"\nMatrix A (3×4):")
print(A)
print(f"\nRank: {rank}")
print(f"Number of vectors: 4")
print(f"Dimension of space: 3")
print("\nSince #vectors > dimension:")
print("→ MUST be DEPENDENT ✗")
print(f"\nIn fact: v₄ = v₁ + v₂ + v₃")
print(f"Verify: {v1} + {v2} + {v3} = {v1 + v2 + v3}")

# ML Application
print("\n" + "="*60)
print("ML Application: Feature Independence")
print("="*60)

# Create dataset with redundant feature
np.random.seed(42)
n_samples = 100

# Independent features
X1 = np.random.randn(n_samples)
X2 = np.random.randn(n_samples)

# Dependent feature: X3 = 2*X1 + 3*X2 + small noise
X3 = 2*X1 + 3*X2 + np.random.randn(n_samples) * 0.01

X = np.column_stack([X1, X2, X3])

print(f"\nDataset shape: {X.shape}")
print(f"Number of features: 3")

rank = np.linalg.matrix_rank(X)
print(f"\nRank of design matrix: {rank}")

if rank < X.shape[1]:
    print(f"\n⚠ WARNING: Rank-deficient!")
    print(f"→ Only {rank} independent features (not 3)")
    print(f"→ Feature 3 is redundant (linear combo of features 1 & 2)")
    print(f"\nConsequences for ML:")
    print("  1. Cannot invert XᵀX for normal equations")
    print("  2. Infinite solutions (model not identifiable)")
    print("  3. Numerical instability")
    print(f"\nSolutions:")
    print("  1. Remove redundant feature")
    print("  2. Use regularization (Ridge/Lasso)")
    print("  3. Use PCA to decorrelate features")
else:
    print(f"\n✓ Full rank: All features are independent")

# Show correlation
corr = np.corrcoef(X.T)
print(f"\nCorrelation matrix:")
print(corr)
print(f"\nNotice: X3 is highly correlated with X1 and X2!")

Linear Independence

Example 1: INDEPENDENT vectors in ℝ²
------------------------------------------------------------
v₁ = [1 0]
v₂ = [0 1]

Matrix A = [v₁ v₂]:
[[1 0]
 [0 1]]

Rank: 2
Determinant: 1.0

Since det ≠ 0 and rank = 2:
→ Vectors are INDEPENDENT ✓
→ Only solution to λ₁v₁ + λ₂v₂ = 0 is λ₁ = λ₂ = 0

Example 2: DEPENDENT vectors in ℝ²
v₁ = [1 2]
v₂ = [2 4]

Notice: v₂ = 2 × v₁

Matrix A = [v₁ v₂]:
[[1 2]
 [2 4]]

Rank: 1
Determinant: 0.0000000000

Since det = 0 and rank < 2:
→ Vectors are DEPENDENT ✗

Non-trivial solution exists:
2v₁ + (-1)v₂ = 0
Verify: 2 × [1 2] + (-1) × [2 4] = [0 0]

Example 3: Testing independence in ℝ³

Case 3a: Independent vectors
v₁ = [1 0 0]
v₂ = [0 1 0]
v₃ = [0 0 1]

Matrix A:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Rank: 3
Determinant: 1.0
→ INDEPENDENT ✓

Case 3b: Dependent vectors
v₁ = [1 2 3]
v₂ = [4 5 6]
v₃ = [5 7 9]

Notice: v₃ = v₁ + v₂
Verify: [1 2 3] + [4 5 6] = [5 7 9]

Matrix A:
[[1 4 5]
 [2 5 7]
 [3 6 9]]

Rank: 2
Determinant: 0.0000000000
→ DEPENDE

## 20. Basis

A basis is a linearly independent set that spans the entire vector space.

**Properties:**
- Minimal spanning set (remove any vector → can't span)
- Maximal independent set (add any vector → becomes dependent)
- Every vector has unique representation

**ML Application:** Principal components, coordinate systems, feature representations.

In [ ]:
"""
Basis of a Vector Space

Definition:
A set of vectors {b₁, b₂, ..., bₙ} is a basis for V if:
1. The vectors are linearly independent
2. The vectors span V

Properties:
- Every vector in V has a UNIQUE representation as a linear combination of basis vectors
- Number of basis vectors = dimension of the space
- Not unique: many different bases for the same space

ML Applications:
- PCA: basis of principal components
- Fourier basis for signals
- Wavelet basis for images
- Change of basis for feature transformation
"""

print("="*60)
print("Basis of Vector Spaces")
print("="*60)

# Example 1: Standard basis for ℝ³
print("\nExample 1: Standard Basis for ℝ³")
print("-"*60)

e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

print(f"e₁ = {e1}")
print(f"e₂ = {e2}")
print(f"e₃ = {e3}")

basis_matrix = np.column_stack([e1, e2, e3])
print(f"\nBasis matrix:")
print(basis_matrix)

# Verify it's a basis
rank = np.linalg.matrix_rank(basis_matrix)
det = np.linalg.det(basis_matrix)

print(f"\nVerification:")
print(f"  Rank: {rank} (= dimension of ℝ³) ✓")
print(f"  Determinant: {det} (≠ 0) ✓")
print(f"  Linearly independent: Yes ✓")
print(f"  Spans ℝ³: Yes ✓")
print(f"\n→ This IS a basis for ℝ³")

# Express arbitrary vector
v = np.array([3, -2, 5])
print(f"\nExpress v = {v} in this basis:")
print(f"v = {v[0]}e₁ + {v[1]}e₂ + {v[2]}e₃")
print(f"  = {v[0]} × {e1} + {v[1]} × {e2} + {v[2]} × {e3}")
print(f"  = {v[0]*e1} + {v[1]*e2} + {v[2]*e3}")
print(f"  = {v[0]*e1 + v[1]*e2 + v[2]*e3}")
print(f"\nCoordinates in standard basis: [{v[0]}, {v[1]}, {v[2]}]")

# Example 2: Alternative basis for ℝ²
print("\n" + "="*60)
print("Example 2: Alternative Basis for ℝ²")
print("="*60)

b1 = np.array([1, 1])
b2 = np.array([1, -1])

print(f"\nNew basis:")
print(f"b₁ = {b1}")
print(f"b₂ = {b2}")

B = np.column_stack([b1, b2])
print(f"\nBasis matrix B:")
print(B)

# Verify it's a basis
rank = np.linalg.matrix_rank(B)
det = np.linalg.det(B)

print(f"\nVerification:")
print(f"  Rank: {rank} (= dimension of ℝ²) ✓")
print(f"  Determinant: {det} (≠ 0) ✓")
print(f"\n→ This IS a basis for ℝ²")

# Express same vector in different bases
v_standard = np.array([3, 1])

print(f"\nVector v = {v_standard} (in standard coordinates)")

# Find coordinates in new basis: solve B @ c = v
coords_new = np.linalg.solve(B, v_standard)

print(f"\nCoordinates in NEW basis: {coords_new}")
print(f"\nMeaning: v = {coords_new[0]:.1f}b₁ + {coords_new[1]:.1f}b₂")

# Verify
v_reconstructed = coords_new[0] * b1 + coords_new[1] * b2
print(f"\nVerification:")
print(f"  {coords_new[0]:.1f} × {b1} + {coords_new[1]:.1f} × {b2}")
print(f"  = {coords_new[0]*b1} + {coords_new[1]*b2}")
print(f"  = {v_reconstructed}")
print(f"  Original v = {v_standard}")
print(f"  Match: {np.allclose(v_reconstructed, v_standard)} ✓")

# Example 3: Non-basis sets
print("\n" + "="*60)
print("Example 3: What is NOT a basis?")
print("="*60)

# Case 1: Linearly dependent (not minimal)
print("\nCase 1: Linearly dependent vectors")
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])  # v3 = v1 + v2

A = np.column_stack([v1, v2, v3])
rank = np.linalg.matrix_rank(A)

print(f"v₁ = {v1}, v₂ = {v2}, v₃ = {v3}")
print(f"Rank: {rank}")
print(f"→ NOT a basis (linearly dependent) ✗")
print(f"→ Redundant: can remove v₃")

# Case 2: Doesn't span (not maximal)
print("\nCase 2: Doesn't span ℝ³")
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
# Missing third vector!

A = np.column_stack([v1, v2])
rank = np.linalg.matrix_rank(A)

print(f"v₁ = {v1}, v₂ = {v2}")
print(f"Rank: {rank}")
print(f"Dimension of ℝ³: 3")
print(f"→ NOT a basis for ℝ³ (doesn't span) ✗")
print(f"→ Only spans a 2D subspace (xy-plane)")
print(f"→ But IS a basis for that subspace!")

# ML Application: PCA Basis
print("\n" + "="*60)
print("ML Application: PCA - Finding Optimal Basis")
print("="*60)

# Generate correlated data
np.random.seed(42)
n_samples = 200

# Data with correlation
mean = [0, 0]
cov = [[3, 1.5],   # Variance = 3, covariance = 1.5
       [1.5, 1]]   # Variance = 1

X = np.random.multivariate_normal(mean, cov, n_samples)

print(f"\nGenerated data: {X.shape}")
print(f"\nCovariance matrix:")
print(np.cov(X.T))

# PCA: Find principal components (new basis)
# Center the data
X_centered = X - X.mean(axis=0)

# Covariance matrix
cov_matrix = np.cov(X_centered.T)

# Eigendecomposition
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Sort by eigenvalue (descending)
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

print(f"\nPrincipal Components (new basis):")
print(f"PC1 = {eigenvectors[:, 0]}")
print(f"PC2 = {eigenvectors[:, 1]}")

print(f"\nEigenvalues (variance explained):")
print(f"PC1: {eigenvalues[0]:.4f}")
print(f"PC2: {eigenvalues[1]:.4f}")

# Verify orthogonality
dot_product = np.dot(eigenvectors[:, 0], eigenvectors[:, 1])
print(f"\nOrthogonality check:")
print(f"PC1 · PC2 = {dot_product:.10f}")
print(f"Is orthogonal: {np.isclose(dot_product, 0)} ✓")

# Verify unit length
norm1 = np.linalg.norm(eigenvectors[:, 0])
norm2 = np.linalg.norm(eigenvectors[:, 1])
print(f"\n||PC1|| = {norm1:.4f} (= 1) ✓")
print(f"||PC2|| = {norm2:.4f} (= 1) ✓")

print(f"\n→ Principal components form an ORTHONORMAL BASIS")
print(f"→ Aligned with directions of maximum variance")
print(f"→ Optimal for dimensionality reduction")

# Transform data to new basis
X_pca = X_centered @ eigenvectors

print(f"\nData in PCA basis:")
print(f"Shape: {X_pca.shape}")
print(f"\nVariance in each PC direction:")
print(f"Var(PC1) = {np.var(X_pca[:, 0]):.4f} (should match eigenvalue {eigenvalues[0]:.4f})")
print(f"Var(PC2) = {np.var(X_pca[:, 1]):.4f} (should match eigenvalue {eigenvalues[1]:.4f})")

print(f"\n→ PCA finds the 'best' basis for your data")
print(f"→ 'Best' = captures most variance in fewest dimensions")

# 📊 Summary Table: Linear Algebra Concepts Covered (Part 2)

| Concept | Definition | Key Property | ML Application |
|---------|------------|--------------|----------------|
| **Vector Space** | Set closed under addition and scalar multiplication | Follows 10 axioms (closure, associativity, commutativity, etc.) | Feature spaces, hypothesis spaces, model capacity |
| **Linear Combination** | Weighted sum of vectors: $y = \lambda_1 v_1 + \dots + \lambda_n v_n$ | Foundation of all linear operations | Neural network layers, feature engineering, ensemble methods |
| **Span** | Set of all possible linear combinations of vectors | Forms a subspace; can be smaller than ambient space | PCA subspaces, feature coverage, rank determination |
| **Linear Independence** | No vector can be written as combination of others | Only trivial solution to $\lambda_1 v_1 + \dots + \lambda_n v_n = 0$ | Feature selection, avoiding multicollinearity, model identifiability |
| **Basis** | Minimal spanning set, maximal independent set | Unique representation for each vector; dimension = # basis vectors | PCA components, coordinate transformations, optimal feature representation |

## Continuation: Part 2 Progress

**Completed so far in Part 2:**
- Vector Space (16)
- Linear Combination (17)
- Span (18)
- Linear Independence (19)
- Basis (20)

**To be continued...:**
- Dimension (21)
- Norms (22-23)
- Inner/Outer/Dot Products (24)
- Eigenvalues/Eigenvectors (25-26)
- SVD & Decompositions (27-31)
- And more...

