In [ ]:
import numpy as np

#System of Linear Equations: Ax = b 

"""
A = [2,1]    x = [x1]       b = [100]
    [1,3]        [x2]           [120]
    
"""

'''Solving the above matrices using numpy'''

# Coefficient matrix
A = np.array([  [2, 1],
                [1, 3]  ])

# Output vector
b = np.array([100, 120])

# Solve for x
x = np.linalg.solve(A, b) #automatically checks if A is square and invertible

print("Solution x =", x)







Solution x = [36. 28.]


In [ ]:
"""
Example Matrices :  A = [1 2]  , B = [5 6]
                        [3 4]        [7 8]
"""
#Element-wise operations are built into numpy arrays, which means addition and multiplication can be done directly

A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

# Matrix Addition
C_add = A+B

print("A + B = \n",C_add)

# Matrix Multiplication
C_mul = A @ B

print("A * B = \n",C_mul)

A + B = 
 [[ 6  8]
 [10 12]]
A * B = 
 [[19 22]
 [43 50]]


In [ ]:
#Properties of matrices

"""
Example Matrices :  A = [1 2]  , B = [5 6] , C = [1 0]
                        [3 4]        [7 8]       [0 1]
"""

A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

C = np.array([[1, 0],
              [0, 1]])  # Identity 2x2

#Associativity Check
assoc1 = (A @ B) @ C
assoc2 = A @ (B @ C)

print("Associativity Check : ", np.allclose(assoc1,assoc2)) #np.allclose() is a NumPy function used to check if two arrays are approximately equal, element-wise, within a small tolerance.
                                                            #Always use np.allclose() when comparing results of matrix operations or any computation involving floating-point numbers
                                                            
# Distributivity Check 
dist1 = (A + B) @ C
dist2 = A @ C + B @ C
print("Distributive check:", np.allclose(dist1, dist2))

# Identity matrix multiplication
print("I @ A =\n", C @ A)
print("A @ I =\n", A @ C)                                                            

#Invisibility 

A_inv = np.linalg.inv(A)
print("A^-1 =\n", A_inv)

# Verify
I = A @ A_inv
print("A @ A^-1 =\n", I)    


#Transpose of a Matrix

A_T = A.T

print("Transpose of A = \n",A_T)
    



Associativity Check :  True
Distributive check: True
I @ A =
 [[1 2]
 [3 4]]
A @ I =
 [[1 2]
 [3 4]]
A^-1 =
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ A^-1 =
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Transpose of A = 
 [[1 3]
 [2 4]]


In [14]:
# Coefficient matrix A
A = np.array([
    [1, 2],
    [3, 4]
])

# Constants vector b
b = np.array([
    [5],
    [11]
])

# Augmented matrix [A | b]
augmented_matrix = np.hstack((A, b))

print("Augmented Matrix:\n", augmented_matrix)

#Pretty print with |
print("\nAugmented Matrix : ")
for row in augmented_matrix:
    print(" ".join(map(str,row[:-1])), "|",row[-1])

Augmented Matrix:
 [[ 1  2  5]
 [ 3  4 11]]

Augmented Matrix : 
1 2 | 5
3 4 | 11
